### ISSUE TITLE
Update all Sentry SDKs

### ISSUE THREAD

**Issue by smeubank** [sentry-demos/application-monitoring#80]
There are some new features on SDKs which we would like to be tested and demo-able.

There are quite some new features for many, and specifically we should make sure that DS features are added, including the new baggage header dynamic sampling contextual data

we should update to latest of the following SDKs

- sentry-javascript (node, react, vue, etc)
  - including sentry-tracing
- sentry-python
- sentry-java
- sentry-ruby
- sentry-cli

**Comment by thinkocapo** [comment]
Hi @smeubank do you know when DS will be commercially available, GA? That would help us prioritize this. Do you have a use case / story defined as well? That would also help us.

Something like this for a Story

_"This is the Aggregation/Metric <x> that was important to the customer, they set it up in Sentry. Then, they did <y> with Dynamic Sampling. Combined, the result is <z>"
“An on-the-fly server-based sampling decision was needed for /<endpoint> because of <something that happened with the customer’s business> and their quota was <x>. As a result, <y> happened, and now everyone is happy and <z> dollars were saved”
“Previously, 30million events were being consumed, but now only 1million because of dynamic sampling sampling”
“Here were all the endpoints, along with how many events came in over a 14 day period. Then here’s where the spike occured…And then he’s the ‘after’ state of the data, as a result of Dynamic Sampling”_

**Comment by thinkocapo** [comment]
@smeubank due to some negative side effects of enabling (not activating) the DS feature flag, this will not longer be considered.

No DS experimentation on testorg-az
